"""add is_active

Revision ID: d8878f4bb63e
Revises: 1d1d304adb97
Create Date: 2026-06-20 22:25:25.042631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8878f4bb63e'
down_revision: Union[str, Sequence[str], None] = '1d1d304adb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('email'), table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'students', ['email'], unique=True)
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
